# Generated by Django 4.1.7 on 2023-02-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_quanity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
